### Пара слов про ошибки
Они в js есть, за них отвечает тип `Error`. Чтобы ошибка всё сломало, её нужно создать и бросить
```javascript
function errorFunction() {
	throw new Error('some error')
	// можно и без new:
	// throw Error('some error')
}
```
Обработка ошибок здесь тоже от других языков особо не отличается
```javascript
try {
	throw new Error("some error")
} catch (err) {
	console.log(err) // Error: some error
}
```

### Зачем нужна асинхронность
Представим, что у вас на сайте есть, при нажатии на которую запускается какая-то долгая функция, например, это может быть запрос на сервер, какое-то действие с задержкой или что угодно ещё. Если попытаться решить эту задачу [в лоб](Зачем%20нужна%20асинхронность.html), мы получим очень неприятный эффект - при нажатии на кнопку вся страница виснет. 
Это происходит потому, что изменение страницы в ответ на действия пользователя (например, перекрашивание ссылки при наведении на неё курсора) требуют вычислительной мощности процессора, а мы уже заняли процессор чем-то другим. Чтобы страница не висла, нужно чередовать выполнение нашей функции с обработкой действий пользователя, то есть выполнять их асинхронно.

Почитать про _event loop_ и то, как работает асинхронность в целом именно в js можно [тут](https://learn.javascript.ru/event-loop)
### Первое решение - коллбеки
Пусть у нас есть функция, принимающая список пользователей и выводящая его в консоль.
```javascript
function printUsers(users) {
	for (let user in users) {
		console.log(user)
	}
}
```
Также у нас есть функция, которая делает запрос на сервер и получает список пользователей
Если бы мы писали синхронный код, то программа получающая список пользователей и выводящая его выглядела бы так:
```javascript
function getUsers(){
	/// users = ...
	// к сожалению, мы ещё не умеем делать запросы
	// поэтому просто представим, что он здесь есть
	return users
}

const loadedUsers = getUsers() // так как запрос выполняется не мнговенно, на этой строчке мы зависнем
printUsers(loadedUsers)
```

Аналогичный код, но с использованием коллбеков будет выглядеть так:
```javascript
function getUsers(callback) {
	/// users = ...
	// к сожалению, мы ещё не умеем делать запросы
	// поэтому просто представим, что он здесь есть
	callback(users)
}

getUsers(printUsers)
// НЕ getUsers(printUsers())
```

Здесь мы передаем функцию `printUsers`, не вызывая её (именно саму функцию, не результат её выполнения) и вызываем её внутри функции `getUsers`, после получения ответа от сервера

#### setTimeout  и setInterval
Так как мы пока не умеем делать запросы, рассмотрим функцию `setTimeout()`, которая используется для выполнения действия с задержкой

Для синхронного ожидания в разных языках обычно существуют функции `sleep()` или `delay()` и код с их использованием выглядит примерно так:
```javascript
console.log(1)
sleep(1000)
console.log(2)
```
При выполнении этой гипотетической (гипотетической, потому что в js нет `sleep()`  или аналогов) программы в консоль выведется 1, а через 1000 миллисекунд 2.
Аналогичная программа с использованием `setTimeout()` будет выглядеть так:
```javascript
setTimeout(() => console.log(2), 1000)
console.log(1)
```
Вначале мы планируем выполнение функции, выводящей 2, после этого (после планирования) выводим 1.
При работе с асинхронным кодом (то есть при работе с почти любым приложением на js) важно помнить, что **порядок строк часто не совпадает с порядком их выполнения**

Что выведет эта программа?
```javascript
let a
setTimeout(() => a = 10, 1000)
console.log(a)
```

```javascript
let a = 5
setTimeout(() => console.log(a), 2000)
setTimeout(() => {
	setTimeout(() => a = 15, 500)
	console.log(a)
	a = 10
}, 1000)
console.log(a)
setTimeout(() => console.log(a), 1250)
```
#### Коллбеки и ошибки
```javascript
function delayedError() {
	setTimeout(() => throw new Error(), 1000)
}

try {
	delayedError()
} catch (err) {
	console.log(err)
} // что произойдёт?
```

Чтобы это исправить, придется переносить обработку ошибок в `setTimeout`, что не очень логично и может запутывать
### Второе решение - промисы
С коллбеками есть ещё одна серьезная проблема, выглядит она примерно так:
```javascript
setTimeout(() => {
	console.log(1)
	setTimeout(() => {
		console.log(2)
		setTimeout(() => {
			if (a === 10) {
				console.log(3)
			}
			setTimeout(() => {
				console.log(4)
				console.log(5)
				setTimeout(() => {
					console.log(6)
					setTimeout(() => console.log(7))
				}, 1000)
			}, 1000)
		}, 2000)
	}, 1000)
}, 1000)
```
При длинных цепочках вызовов код получается очень вложенным и трудночитаемым
- 2000 задержки относится к какому таймауту? 
- На первый взгляд, может показаться, что 3 4 и 5 находятся на одном уровне, и выведутся одновременно, хотя это не так
Такую ситуацию программисты назвали _callback hell_ и решили, что надо что-то менять

Одно из решений - промисы 
```javascript
function getUsers(){
	/// users = ...
	// к сожалению, мы ещё не умеем делать запросы
	// поэтому просто представим, что он здесь есть
	return users
}

const loadedUsers = getUsers() // так как запрос выполняется не мнговенно, на этой строчке мы зависнем
printUsers(loadedUsers)
```
Перепишем этот код ещё раз, теперь используя промисы
```javascript
function getUsers(){
	return new Promise((resolve, reject) => {
		// users = ...
		// к сожалению, мы ещё не умеем делать асинхронные запросы
		// поэтому просто представим, что он здесь есть
		resolve(users)
	})
}
let promise = getUsers()
promose.then(users => printUsers(users))
// или
getUsers().then(users => printUsers(users))
```
Здесь функция `getUsers()` возвращает промис - обещание результата. У объекта типа 
`Promise` есть 3 метода 
- then - основной метод, позволяет прикрепить к промису функцию, которая выполнится по его завершению эта функция должна принимать один аргумент - результат выполнения промиса. Вторым аргументом можно передать ещё одну, она будет вызвана в случае ошибки и единственным аргументом должна принимать эту ошибку
```javascript 
promise.then(success => // что-то)
// или
promise.then(
			success => // что-то,
			error =>  // что-то
)
```
- catch - позволяет прикрепить обработчик на какой-то определённый тип ошибки
```javascript
promise.catch((SomeError, error => alert(error))
```
Это уже значительно удобнее, чем было с коллбеками, потому что теперь код, вызываемый в случае успеха и ошибки находится рядом:
```javascript
someSuspiciousFunction()
	.then(() => console.log("победа"))
	.catch(Error, err => console.log("я так и знал, что она не работает"))
```
- finally - позволяет прикрепить функцию, которая будет вызвана вне зависимости от результата выполнения промиса
```javascript
promise.finally(() => conn.close()) // например, можно закрыть соединение, остановить анимацию загрузки
```
Похоже на try-catch-finally, только синтаксис другой

Теперь посмотрим поближе на создание промиса
```javascript
function promise() {
	return new Promise((resolve, reject) => {
		// resolve и reject - это функции, которые функция, оборачиваемая в промис дожна принимать как аргументы
		setTimeout(() => {
			if (Math.random() >= 0.5) {
				resolve("success") // в случае успешного завершения работы функции, нужно вывать resolve и пеердать туда результат работы
				// Дальше он попадет в функцию обработчик, прикреплённую при помощи .then() 
			} else {
				reject(new Error('???')) // в случае ошибки, нужно вызвать reject и передать в него ошибку
				// Эта ошибка также попадёт в обработчик ошибок, прикреплённый к промису
			}
		}, 1000) 
	})
}

promise()
	.then(
		success => console.log(success),
		error => console.log(error)
	)
console.log(1)
```
Выглядит страшнее, чем коллбеки, но создавать промисы вам придется очень редко, часто функции предоставляемые фреймворками или api браузера будут возвращать промисы, с этим нужно уметь работать

Что выведет эта программа*
```javascript
new Promise((resolve, reject) => {
	resolve(1)
}).then(data => console.log(data))
console.log(2)
```

#### Цепочки then'ов
Функции-обработчики могут не только принимать значения, но и возвращать что-то. То, что вернет функция-обработчик попадёт в следующий .then()

```javascript
new Promise((resolve, reject) => {
	resolve(1)
})
	.then(data => {
		console.log(data)
		return 2
	})
	.then(data => {
		console.log(data)
		return 3
	})
	.then(data => {
		console.log(data)
	})
```
Это может быть нужно, например, для цепочки запросов
```javascript
// fetch - фукцния для отправки запросов, мы с ней ещё познакомимся, но попозже
// она возвращает промис, в случае успешного выполения в нём окажется ответ сервера
fetch('/current_user')
	.then(data => fetch(`/profile_picture/${data}`))
	.then(data => ...) // выводим полученную картинку
```
Функция, переданная во второй `then` будет вызвана после выполнения обоих запросов

### Третье решение - async/await

Если посмотреть на цепочки `then'ов`, то они похожи на обычный синхронный код - строчки выполняются по порядку, но получается немного громоздко из-за необходимости постоянно писать`.then()`
Чтобы избавиться от этой громоздкости придумали асинхронные функции, обозначаемые ключевым словом `async`. Чтобы дождаться выполнения другого асинхронного действия внутри такой функции используется слово `await`

```javascript
async function getUsers(){
	// users = ...
	// к сожалению, мы ещё не умеем делать асинхронные запросы
	// поэтому просто представим, что он здесь есть
	return users
}

async function processUsers() {
	let users = await getUsers() 
	printUsers(users) // Эта строка будет выполнена только после завершения работы getUsers() и получения результата
	// выглядит как обычный синхронный код, но функция, ожидаемая через await
	// не забивает поток выполнения, то есть страница не зависнет
}

processUsers()
```

Цепочки вызовов из нескольких последовательных асинхронных функций выглядят очень просто и читаемо:
```javascript
async function asyncChain() {
	let res1 = await request1()
	let res2 = await request2(res1)
	let res3 = await request3(res1, res2)
	console.log(res3)
}
```
Ключевым отличием асинхронной функции от обычной является то, что переход на следующую строчку происходит мгновенно (если перед ней нет `await`)
```javascript
async function f1(a) {
	// await какое-то долгое действие
	console.log(a)
}
async function f2() {
	await f1(3)
	console.log(4)
}
f1(1)
console.log(2)
f2()
// выведет 2 1 3 4
```
Но что делать, если в синхронном коде нужно дождаться выполнения асинхронной функции?
На самом деле под капотом асинхронная функция - это промис, и работать с ней можно также
```javascript
async function f1() {
	return 'success'
}
f1().then(data => console.log(data))
```
Зная это, можно переписать цепочку запросов с промисов на асинки
```javascript
async function loadPicture() {
	let user = await fetch('/current_user')
	let picture = await fetch(`/profile_picture/${data}`))
	// выводим полученную картинку
}

loadPicture().catch(error => alert("Ошибка при загрузке картинки"))
```


# Задания
1) Реализуйте функцию delay(ms), которая принимает задержку в миллисекундах и возвращает промис, который разрешится через это время (аналог setTimeout, но не на коллбеках, а на промисах) 
```javascript
delay(500).then((res) => alert('1'))
```
2) Реализуйте функцию, которая принимает функцию-коллбек для успешного выполнения и функцию-коллбек для ошибки, генерирует случайное число от 0 до 2000, ждёт столько миллисекунд и вызывает случайную (из этих двух) функцию, передавая туда сгенерированное число
```javascript
const myCallback = (t) => console.log(t)
const myOnError = (t) => console.log(`error, ${t}`)
func(myCallback, myOnError) // ждёт, потом пишет в консоль
```
3) сделайте такую же функцию через промисы и асинки (вызывать её нужно будет немного по-другому, но идейно нужно чтобы все работало также, как код приведенный в прошлом задании)
   _подсказка: возможно, стоит использовать функцию из первого задания_
```javascript
func().then(myCallback).catch(myOnError) // пример использования
```
3) `fetch` - это асинхронная функция, позволяющая делать http запросы. Мы еще поговорим о ней на следующих занятиях, сейчас нас интересует только то, что она асинхронная.
   Используется она примерно так:
```javascript
function baseRequest(url) {
    return async function () {
        const value = await fetch(url)
        if (value.ok) {
            return value.json()
        } else {
            throw Error("error in request")
        }
    }
}
const sucсessfulRequest = baseRequest('http://httpbin.org/get?param1=test')
const badRequest = baseRequest('http://httpbin.org/status/404')
const randomRequest = async () => Math.random() >= 0.5 ? await sucessfullRequest() : await badRequest()
```
Используя функцию эти 3 функции реализуйте:
- функцию, которая делает 2 запроса параллельно, выводя результаты этих запросов по мере их появления
- функцию, которая делает 2 запроса последовательно, причем 2 запрос делается только если 1 прошел успешно. Вывести нужно результат обоих сразу.
- функцию, которая делает n запросов, выводя только результат первого
- функцию, которая делает n запросов, выводя только результат первого успешного (те, что падают с ошибкой, игнорируем)
Часть заданий нужно сделать через промисы, часть через асинки (какие как - на ваш выбор, но нельзя использовать везде одно и то же)